name: Prepare release draft
on: workflow_dispatch

jobs:
  github-release-draft:
    runs-on: ubuntu-24.04

    permissions:
      id-token: write
      contents: write

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Build gem
        id: version
        run: |
          echo "version=$(ruby -e 'puts Gem::Specification::load(Dir.glob("*.gemspec").first).version')" >> $GITHUB_OUTPUT
      - uses: rubygems/release-gem@v1

  github-release:
    name: Attach gem to GitHub release and publish
    needs: release-gem
    runs-on: ubuntu-24.04 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      GEM_VERSION: ${{ needs.release-gem.outputs.version }}

    permissions:
      contents: write

    steps:
      - name: Download from RubyGems
        run: |
          gem fetch tobee --version ${GEM_VERSION} --verbose
      - name: Attach to existing release draft
        run: |
          gh release upload "v${GEM_VERSION}" *.gem --clobber
          gh release edit "v${GEM_VERSION}" --draft=false
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
