name: First

on:
  push:
    branches:
      - release

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.8
      - run: bundle install
      - run: |
          gem --version
          bundle --version
      # - name: Configure RubyGems to use GitHub Packages
      #   run: |
      #     mkdir -p ~/.gem
      #     echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
      #     chmod 600 ~/.gem/credentials

      # - run: gem install -V equilibrium -s https://rubygems.pkg.github.com/tonycthsu

      - name: Configure .gemrc (another alternative)
        run: |
          cat > ~/.gemrc << EOF
          ---
          :sources:
          - https://rubygems.org/
          - https://rubygems.pkg.github.com/tonycthsu/
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          EOF

          gem install -V equilibrium -s https://rubygems.pkg.github.com/tonycthsu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
